apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identityserver4admin.fullname" . }}-identity-data
  labels:
    {{- include "identityserver4admin.labelsAdmin" . | nindent 4 }}
data:
  identitydata.json: |
{{ tpl (.Files.Get "config/identitydata.json") . | printf "%s" | indent 4}}