apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    {{- include "identityserver4admin.labelsAdmin" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  {{- if .Values.admin.ssl.enabled }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  {{- else }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "identityserver4admin.selectorLabelsAdmin" . | nindent 4 }}
