{{- if .Values.admin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identityserver4admin.serviceAccountNameAdmin" . }}
  labels:
    {{- include "identityserver4admin.labelsAdmin" . | nindent 4 }}
  {{- with .Values.admin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
