apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identityserver4admin.fullname" . }}-identity-serverdata
  labels:
    {{- include "identityserver4admin.labelsAdmin" . | nindent 4 }}
data:
  identityserverdata.json: |
{{ tpl (.Files.Get "config/identityserverdata.json") . | printf "%s" | indent 4}}