apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identityserver4admin.fullname" . }}-admin-app-settings
  labels:
    {{- include "identityserver4admin.labelsAdmin" . | nindent 4 }}
data:
  appsettings.json: |
{{ tpl (.Files.Get "config/admin-appsettings.json") . | printf "%s" | indent 4}}
