{{- if .Values.api.enabled }}
{{- if .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identityserver4admin.serviceAccountNameApi" . }}
  labels:
    {{- include "identityserver4admin.labelsApi" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
