{{- if and (.Values.certificates.certManager.enabled) (.Values.api.ssl.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.api.ssl.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.api.ssl.secretName }}
  issuerRef:
    name: {{ .Values.certificates.certManager.issuerRef.name }}
    kind: {{ .Values.certificates.certManager.issuerRef.kind }}
  commonName: {{ .Values.api.ssl.secretName }}
  dnsNames:
  - {{ .Values.api.domainName }}
{{- end }}
