apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "identityserver4admin.labelsApi" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    {{- if .Values.api.ssl.enabled }}
    - port: {{ .Values.api.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- else }}
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "identityserver4admin.selectorLabelsApi" . | nindent 4 }}
