apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identityserver4admin.fullname" . }}-api-app-settings
  labels:
    {{- include "identityserver4admin.labelsApi" . | nindent 4 }}
data:
  appsettings.json: |
{{ tpl (.Files.Get "config/api-appsettings.json") . | printf "%s" | indent 4}}