apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: database-credentials
data:
  ConnectionStrings__ConfigurationDbConnection: {{ include "databaseConnectionString" . | b64enc | quote }}
  ConnectionStrings__PersistedGrantDbConnection: {{ include "databaseConnectionString" . | b64enc | quote }}
  ConnectionStrings__IdentityDbConnection: {{ include "databaseConnectionString" . | b64enc | quote }}
  ConnectionStrings__AdminLogDbConnection: {{ include "databaseConnectionString" . | b64enc | quote }}
  ConnectionStrings__AdminAuditLogDbConnection: {{ include "databaseConnectionString" . | b64enc | quote }}
  ConnectionStrings__DataProtectionDbConnection: {{ include "databaseConnectionString" . | b64enc | quote }}
