apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identityserver4admin.fullname" . }}-identity-app-settings
  labels:
    {{- include "identityserver4admin.labelsIdentity" . | nindent 4 }}
data:
  appsettings.json: |
{{ tpl (.Files.Get "config/identity-appsettings.json") . | printf "%s" | indent 4}}