apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-identity
  labels:
    {{- include "identityserver4admin.labelsIdentity" . | nindent 4 }}
spec:
  type: {{ .Values.identity.service.type }}
  ports:
    {{- if .Values.identity.ssl.enabled }}
    - port: {{ .Values.identity.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- else }}
    - port: {{ .Values.identity.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "identityserver4admin.selectorLabelsIdentity" . | nindent 4 }}
