apiVersion: v1
kind: Service
metadata:
  name: {{ include "identityserver4admin.fullname" . }}-identity
  labels:
    {{- include "identityserver4admin.labelsIdentity" . | nindent 4 }}
spec:
  type: {{ .Values.identity.service.type }}
  ports:
    - port: {{ .Values.identity.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "identityserver4admin.selectorLabelsIdentity" . | nindent 4 }}
