{{- if .Values.identity.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "identityserver4admin.fullname" . }}
  labels:
    {{- include "identityserver4admin.labelsIdentity" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "identityserver4admin.fullname" . }}
  minReplicas: {{ .Values.identity.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.identity.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.identity.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.identity.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.identity.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.identity.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
