apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  labels:
    {{- include "identityserver4admin.labelsMssql" . | nindent 4 }}
type: Opaque
data:
  sa_password : {{ .Values.mssql.sa_password | b64enc | quote}}