apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mssql
  labels:
    {{- include "identityserver4admin.labelsMssql" . | nindent 4 }}
spec:
  type: {{ .Values.mssql.service.type }}
  ports:
    - port: {{ .Values.mssql.service.port }}
      targetPort: {{ .Values.mssql.service.port }}
      protocol: TCP
  selector:
    {{- include "identityserver4admin.selectorLabelsMssql" . | nindent 4 }}