{{- if .Values.mssql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mssql-secret
  labels:
    {{- include "mssql.labelsMssql" . | nindent 4 }}
type: Opaque
data:
  sa_password : {{ .Values.mssql.sa_password | b64enc | quote}}

{{- end }}