apiVersion: v1
entries:
  identityserver4admin:
  - apiVersion: v2
    appVersion: 2.0.1
    created: "2021-05-23T16:07:10.467301378Z"
    description: A Helm chart for IdentityServer4Admin
    digest: 2f9e7d462bae9036898af1dba3b31e6799d91c1639537f6213a83506c46c1182
    name: identityserver4admin
    type: application
    urls:
    - https://bravecobra.github.io/identityserver4.admin-helm/charts/identityserver4admin-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 2.0.1
    created: "2021-05-23T15:20:48.861876832Z"
    description: A Helm chart for IdentityServer4Admin
    digest: 2ae9ceb0ac6dd59cec68a717c4e2b60833a610ca2a3ee3bdfeb31a0d5fa2719b
    name: identityserver4admin
    type: application
    urls:
    - https://bravecobra.github.io/identityserver4.admin-helm/charts/identityserver4admin-0.1.0.tgz
    version: 0.1.0
generated: "2021-05-23T16:07:10.465786647Z"
